# Generated by Django 4.2.7 on 2025-09-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(choices=[('Rice', 'Rice'), ('Wheat', 'Wheat'), ('Maize', 'Maize'), ('Sugarcane', 'Sugarcane'), ('Cotton', 'Cotton'), ('Soybean', 'Soybean'), ('Potato', 'Potato'), ('Tomato', 'Tomato'), ('Onion', 'Onion'), ('Chili', 'Chili')], max_length=50)),
                ('season', models.CharField(choices=[('Kharif', 'Kharif'), ('Rabi', 'Rabi'), ('Zaid', 'Zaid'), ('Monsoon', 'Monsoon'), ('Winter', 'Winter'), ('Summer', 'Summer')], max_length=50)),
                ('soil', models.CharField(choices=[('Clay', 'Clay'), ('Sandy', 'Sandy'), ('Loamy', 'Loamy'), ('Silty', 'Silty'), ('Peaty', 'Peaty'), ('Chalky', 'Chalky')], max_length=50)),
                ('preference', models.CharField(choices=[('Organic', 'Organic'), ('Inorganic', 'Inorganic'), ('Mixed', 'Mixed')], max_length=50)),
                ('location_name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('result_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['crop'], name='recommendat_crop_8c30f2_idx'), models.Index(fields=['season'], name='recommendat_season_bbdeb0_idx'), models.Index(fields=['created_at'], name='recommendat_created_0cbb1c_idx'), models.Index(fields=['location_name'], name='recommendat_locatio_ae18b7_idx')],
            },
        ),
    ]
